"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.11.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

#from django.core.urlresolvers import reverse_lazy

LOGIN_REDIRECT_URL = '/polls/'


#LOGIN_URL = reverse_lazy('login')
#LOGOUT_URL = reverse_lazy('logout')
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'y!=_ghk3nq!2_^=m45&vbi_n)93ky$cr9j^i-ne9*8@x+isnts'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'admin_view_permission',
    'jet.dashboard',
    'jet',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',#moi them
    'polls.apps.PollsConfig',
    'nested_inline',
    'froala_editor',
    'controlcenter',
    'import_export',
    'rangefilter',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mysite.middleware.LoginRequiredMiddleware'
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [], #os.path.join(BASE_DIR,'templates'
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'django1',
        'USER' : 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

# EMAIL_HOST = 'localhost'
# EMAIL_PORT = 1025

LOGIN_URL ='/polls/login'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'mysite/media')

LOGIN_EXEMPT_URLS = (
    r'^polls/logout/$',
    r'^polls/$',
    r'^polls/register/$',
    r'^admin/',
    r'^polls/reset-password/$',
    r'^polls/reset-password/done/$',
    r'^polls/reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
    r'^polls/reset-password/complete/$',
    r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',

)

#
# JET_SIDE_MENU_ITEMS = [
#     {'app_label': 'auth', 'items': [
#         {'name': 'group'},
#         {'name': 'user'},
#         {'name': 'userprofile'},
#     ]},
#     {'app_label': 'recruitment', 'items': [
#         {'name': 'recruitmentform'},
#         {'name': 'recruitment'},
#     ]},
#     {'app_label': 'project', 'items': [
#             {'name': 'project'},
#             {'name': 'publishedevent'},
#             {'name': 'registerevent'},
#             {'name': 'subproject'},
#             {'name': 'task'},
#     ]},
# ]
# JET_SIDE_MENU_ITEMS = [
#     {'app_label': 'auth', 'items': [
#         {'name': 'group'},
#         {'name': 'user'},
#     ]},
#     {'app_label': 'polls', 'items': [
#         {'name': 'project'},
#         {'name': 'publishedevent'},
#         {'name': 'recruitmentform'},
#         {'name': 'recruitment'},
#         {'name': 'registerevent'},
#         {'name': 'subproject'},
#         {'name': 'task'},
#         {'name': 'userprofile'},
#     ]},
# ]
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_USE_SSL = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'vietnamaiesec@gmail.com'
EMAIL_HOST_PASSWORD = 'leseqhtwsdiobzez'

CONTROLCENTER_DASHBOARDS = (
    'polls.dashboard.MyDashboard',
)

ADMIN_VIEW_PERMISSION_MODELS = [
    'auth.User',
    'EmailContent',
    'RegisterEvent',
    'LocalCommittee',
    'ProjectOfKind',
    'PublishedEvent',
    'Project',
    'SubProject',
    'Task',
    'Creatia',
    'Questionnaire',
    'RecruitmentForm',
    'Recruitment',
    'UserProfile',
]
